# Addis Ababa Dataset

## Extract CSV File

In [1]:
import pandas

data = pandas.read_csv('Addis_data.csv')

### Change Columns to Readable Features

In [9]:
import util

data.columns = util.NEW_NAMES

In [8]:
data[:3].describe()

,lat,long,water_source_drinking,water_location_drinking,water_interruptions_drinking,water_unavailable,water_treated,water_quality_concerns,water_satisfaction,water_drinking_cooking_same,...,healthcare_distance,healthcare_satisfaction,education_used,bl_sd45,education_distance,satisfaction_num_classrooms,satisfaction_num_textbooks,satisfaction_cost_textbooks,satisfaction_education,ID
count,3.000000,3.000000,3.0,3.000000,3.000000,2.000000,3.0,3.0,3.000000,3.0,...,3.0,3.000000,3.000000,3.000000,3.0,3.000000,3.000000,3.000000,3.000000,3.0
mean,9.091008,38.527474,1.0,2.666667,1.333333,8.000000,2.0,2.0,1.666667,1.0,...,5.0,1.666667,1.666667,2.333333,15.0,-591.666667,-591.666667,-591.666667,-591.666667,2.0
std,0.001360,0.000524,0.0,0.577350,0.577350,8.485281,0.0,0.0,0.577350,0.0,...,0.0,0.577350,0.577350,0.577350,0.0,513.264389,513.264389,513.264389,513.264389,1.0
min,9.089951,38.526909,1.0,2.000000,1.000000,2.000000,2.0,2.0,1.000000,1.0,...,5.0,1.000000,1.000000,2.000000,15.0,-888.000000,-888.000000,-888.000000,-888.000000,1.0
25%,9.090241,38.527239,1.0,2.500000,1.000000,5.000000,2.0,2.0,1.500000,1.0,...,5.0,1.500000,1.500000,2.000000,15.0,-888.000000,-888.000000,-888.000000,-888.000000,1.5
50%,9.090530,38.527569,1.0,3.000000,1.000000,8.000000,2.0,2.0,2.000000,1.0,...,5.0,2.000000,2.000000,2.000000,15.0,-888.000000,-888.000000,-888.000000,-888.000000,2.0
75%,9.091537,38.527756,1.0,3.000000,1.500000,11.000000,2.0,2.0,2.000000,1.0,...,5.0,2.000000,2.000000,2.500000,15.0,-443.500000,-443.500000,-443.500000,-443.500000,2.5
max,9.092543,38.527943,1.0,3.000000,2.000000,14.000000,2.0,2.0,2.000000,1.0,...,5.0,2.000000,2.000000,3.000000,15.0,1.000000,1.000000,1.000000,1.000000,3.0